version: '3'

services:
  database:
    image: 'microsoft/mssql-server-linux'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
  magisco-backend:
    image: magisco-backend
    build:
      context: .
      dockerfile: magisco-backend/Dockerfile
volumes:
  mssql_data: