version: '3'

services:
  database:
    image: 'microsoft/mssql-server-linux'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
  linqu-backend:
    image: linqu-backend
    build:
      context: ./linqu-backend
      dockerfile: Dockerfile
volumes:
  mssql_data: